/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : ChapterId,
  'title' : string,
  'content' : string,
  'chapterNumber' : bigint,
  'createdAt' : Timestamp,
  'novelId' : NovelId,
}
export type ChapterId = bigint;
export interface CollabSessionPublic {
  'lastUpdated' : Timestamp,
  'chapterId' : ChapterId,
  'novelId' : NovelId,
  'lastContent' : string,
  'activeEditors' : Array<UserId>,
}
export interface CreateChapterRequest {
  'title' : string,
  'content' : string,
  'chapterNumber' : bigint,
  'novelId' : NovelId,
}
export interface CreateNovelRequest {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'coverImage' : string,
  'genre' : string,
}
export type NovelId = bigint;
export interface NovelPublic {
  'id' : NovelId,
  'title' : string,
  'ratingCount' : bigint,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'authorName' : string,
  'description' : string,
  'coverImage' : string,
  'genre' : string,
  'coAuthors' : Array<UserId>,
  'totalReads' : bigint,
  'authorPrincipal' : UserId,
  'avgRating' : number,
}
export interface RatingRequest { 'novelId' : NovelId, 'rating' : bigint }
export interface ReadingProgressPublic {
  'userId' : UserId,
  'lastChapterNumber' : bigint,
  'lastChapterId' : ChapterId,
  'novelId' : NovelId,
  'updatedAt' : Timestamp,
  'percentComplete' : number,
}
export type SaveDraftResult = { 'ok' : null } |
  { 'err' : string };
export interface SaveProgressRequest {
  'lastChapterNumber' : bigint,
  'lastChapterId' : ChapterId,
  'novelId' : NovelId,
  'percentComplete' : number,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'chaptersRead' : bigint,
  'createdAt' : Timestamp,
  'novelsRead' : bigint,
  'avatarUrl' : string,
  'isAuthor' : boolean,
}
export interface _SERVICE {
  'acceptFriendRequest' : ActorMethod<[UserId], boolean>,
  'addChapter' : ActorMethod<[CreateChapterRequest], bigint>,
  'addCoAuthor' : ActorMethod<[NovelId, Principal], boolean>,
  'becomeAuthor' : ActorMethod<[], boolean>,
  'createNovel' : ActorMethod<[CreateNovelRequest, string], bigint>,
  'createProfile' : ActorMethod<[string, string, string], boolean>,
  'declineFriendRequest' : ActorMethod<[UserId], boolean>,
  'filterByGenre' : ActorMethod<[string], Array<NovelPublic>>,
  'getActiveSessions' : ActorMethod<[NovelId], Array<CollabSessionPublic>>,
  'getAllNovels' : ActorMethod<[], Array<NovelPublic>>,
  'getChapter' : ActorMethod<[ChapterId], [] | [Chapter]>,
  'getChapterDraft' : ActorMethod<[ChapterId], [] | [CollabSessionPublic]>,
  'getFriends' : ActorMethod<[], Array<UserId>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getNovel' : ActorMethod<[NovelId], [] | [NovelPublic]>,
  'getNovelChapters' : ActorMethod<[NovelId], Array<Chapter>>,
  'getPendingRequests' : ActorMethod<[], Array<UserId>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getProgress' : ActorMethod<[NovelId], [] | [ReadingProgressPublic]>,
  'getReadingHistory' : ActorMethod<[], Array<ReadingProgressPublic>>,
  'getTopNovels' : ActorMethod<[], Array<NovelPublic>>,
  'incrementReadCount' : ActorMethod<[ChapterId], undefined>,
  'joinCollabSession' : ActorMethod<[ChapterId, NovelId], undefined>,
  'leaveCollabSession' : ActorMethod<[ChapterId], undefined>,
  'publishChapter' : ActorMethod<[ChapterId], SaveDraftResult>,
  'rateNovel' : ActorMethod<[RatingRequest], boolean>,
  'removeCoAuthor' : ActorMethod<[NovelId, Principal], boolean>,
  'removeFriend' : ActorMethod<[UserId], boolean>,
  'saveChapterDraft' : ActorMethod<[ChapterId, string], SaveDraftResult>,
  'saveProgress' : ActorMethod<[SaveProgressRequest], boolean>,
  'searchNovels' : ActorMethod<[string], Array<NovelPublic>>,
  'searchUsers' : ActorMethod<[string], Array<UserProfilePublic>>,
  'sendFriendRequest' : ActorMethod<[UserId], boolean>,
  'updateChapter' : ActorMethod<[ChapterId, string, string], boolean>,
  'updateNovel' : ActorMethod<[NovelId, CreateNovelRequest], boolean>,
  'updateProfile' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];