/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const NovelId = IDL.Nat;
export const CreateChapterRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'novelId' : NovelId,
});
export const CreateNovelRequest = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'coverImage' : IDL.Text,
  'genre' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const NovelPublic = IDL.Record({
  'id' : NovelId,
  'title' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'coverImage' : IDL.Text,
  'genre' : IDL.Text,
  'coAuthors' : IDL.Vec(UserId),
  'totalReads' : IDL.Nat,
  'authorPrincipal' : UserId,
  'avgRating' : IDL.Float64,
});
export const ChapterId = IDL.Nat;
export const CollabSessionPublic = IDL.Record({
  'lastUpdated' : Timestamp,
  'chapterId' : ChapterId,
  'novelId' : NovelId,
  'lastContent' : IDL.Text,
  'activeEditors' : IDL.Vec(UserId),
});
export const Chapter = IDL.Record({
  'id' : ChapterId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'createdAt' : Timestamp,
  'novelId' : NovelId,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'chaptersRead' : IDL.Nat,
  'createdAt' : Timestamp,
  'novelsRead' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'isAuthor' : IDL.Bool,
});
export const ReadingProgressPublic = IDL.Record({
  'userId' : UserId,
  'lastChapterNumber' : IDL.Nat,
  'lastChapterId' : ChapterId,
  'novelId' : NovelId,
  'updatedAt' : Timestamp,
  'percentComplete' : IDL.Float64,
});
export const SaveDraftResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const RatingRequest = IDL.Record({
  'novelId' : NovelId,
  'rating' : IDL.Nat,
});
export const SaveProgressRequest = IDL.Record({
  'lastChapterNumber' : IDL.Nat,
  'lastChapterId' : ChapterId,
  'novelId' : NovelId,
  'percentComplete' : IDL.Float64,
});

export const idlService = IDL.Service({
  'acceptFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'addChapter' : IDL.Func([CreateChapterRequest], [IDL.Nat], []),
  'addCoAuthor' : IDL.Func([NovelId, IDL.Principal], [IDL.Bool], []),
  'becomeAuthor' : IDL.Func([], [IDL.Bool], []),
  'createNovel' : IDL.Func([CreateNovelRequest, IDL.Text], [IDL.Nat], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'declineFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'filterByGenre' : IDL.Func([IDL.Text], [IDL.Vec(NovelPublic)], ['query']),
  'getActiveSessions' : IDL.Func(
      [NovelId],
      [IDL.Vec(CollabSessionPublic)],
      ['query'],
    ),
  'getAllNovels' : IDL.Func([], [IDL.Vec(NovelPublic)], ['query']),
  'getChapter' : IDL.Func([ChapterId], [IDL.Opt(Chapter)], ['query']),
  'getChapterDraft' : IDL.Func(
      [ChapterId],
      [IDL.Opt(CollabSessionPublic)],
      ['query'],
    ),
  'getFriends' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getNovel' : IDL.Func([NovelId], [IDL.Opt(NovelPublic)], ['query']),
  'getNovelChapters' : IDL.Func([NovelId], [IDL.Vec(Chapter)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
  'getProgress' : IDL.Func(
      [NovelId],
      [IDL.Opt(ReadingProgressPublic)],
      ['query'],
    ),
  'getReadingHistory' : IDL.Func(
      [],
      [IDL.Vec(ReadingProgressPublic)],
      ['query'],
    ),
  'getTopNovels' : IDL.Func([], [IDL.Vec(NovelPublic)], ['query']),
  'incrementReadCount' : IDL.Func([ChapterId], [], []),
  'joinCollabSession' : IDL.Func([ChapterId, NovelId], [], []),
  'leaveCollabSession' : IDL.Func([ChapterId], [], []),
  'publishChapter' : IDL.Func([ChapterId], [SaveDraftResult], []),
  'rateNovel' : IDL.Func([RatingRequest], [IDL.Bool], []),
  'removeCoAuthor' : IDL.Func([NovelId, IDL.Principal], [IDL.Bool], []),
  'removeFriend' : IDL.Func([UserId], [IDL.Bool], []),
  'saveChapterDraft' : IDL.Func([ChapterId, IDL.Text], [SaveDraftResult], []),
  'saveProgress' : IDL.Func([SaveProgressRequest], [IDL.Bool], []),
  'searchNovels' : IDL.Func([IDL.Text], [IDL.Vec(NovelPublic)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfilePublic)], ['query']),
  'sendFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'updateChapter' : IDL.Func([ChapterId, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateNovel' : IDL.Func([NovelId, CreateNovelRequest], [IDL.Bool], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const NovelId = IDL.Nat;
  const CreateChapterRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'novelId' : NovelId,
  });
  const CreateNovelRequest = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'coverImage' : IDL.Text,
    'genre' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const NovelPublic = IDL.Record({
    'id' : NovelId,
    'title' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'coverImage' : IDL.Text,
    'genre' : IDL.Text,
    'coAuthors' : IDL.Vec(UserId),
    'totalReads' : IDL.Nat,
    'authorPrincipal' : UserId,
    'avgRating' : IDL.Float64,
  });
  const ChapterId = IDL.Nat;
  const CollabSessionPublic = IDL.Record({
    'lastUpdated' : Timestamp,
    'chapterId' : ChapterId,
    'novelId' : NovelId,
    'lastContent' : IDL.Text,
    'activeEditors' : IDL.Vec(UserId),
  });
  const Chapter = IDL.Record({
    'id' : ChapterId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'createdAt' : Timestamp,
    'novelId' : NovelId,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'chaptersRead' : IDL.Nat,
    'createdAt' : Timestamp,
    'novelsRead' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'isAuthor' : IDL.Bool,
  });
  const ReadingProgressPublic = IDL.Record({
    'userId' : UserId,
    'lastChapterNumber' : IDL.Nat,
    'lastChapterId' : ChapterId,
    'novelId' : NovelId,
    'updatedAt' : Timestamp,
    'percentComplete' : IDL.Float64,
  });
  const SaveDraftResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const RatingRequest = IDL.Record({ 'novelId' : NovelId, 'rating' : IDL.Nat });
  const SaveProgressRequest = IDL.Record({
    'lastChapterNumber' : IDL.Nat,
    'lastChapterId' : ChapterId,
    'novelId' : NovelId,
    'percentComplete' : IDL.Float64,
  });
  
  return IDL.Service({
    'acceptFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'addChapter' : IDL.Func([CreateChapterRequest], [IDL.Nat], []),
    'addCoAuthor' : IDL.Func([NovelId, IDL.Principal], [IDL.Bool], []),
    'becomeAuthor' : IDL.Func([], [IDL.Bool], []),
    'createNovel' : IDL.Func([CreateNovelRequest, IDL.Text], [IDL.Nat], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'declineFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'filterByGenre' : IDL.Func([IDL.Text], [IDL.Vec(NovelPublic)], ['query']),
    'getActiveSessions' : IDL.Func(
        [NovelId],
        [IDL.Vec(CollabSessionPublic)],
        ['query'],
      ),
    'getAllNovels' : IDL.Func([], [IDL.Vec(NovelPublic)], ['query']),
    'getChapter' : IDL.Func([ChapterId], [IDL.Opt(Chapter)], ['query']),
    'getChapterDraft' : IDL.Func(
        [ChapterId],
        [IDL.Opt(CollabSessionPublic)],
        ['query'],
      ),
    'getFriends' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getNovel' : IDL.Func([NovelId], [IDL.Opt(NovelPublic)], ['query']),
    'getNovelChapters' : IDL.Func([NovelId], [IDL.Vec(Chapter)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
    'getProgress' : IDL.Func(
        [NovelId],
        [IDL.Opt(ReadingProgressPublic)],
        ['query'],
      ),
    'getReadingHistory' : IDL.Func(
        [],
        [IDL.Vec(ReadingProgressPublic)],
        ['query'],
      ),
    'getTopNovels' : IDL.Func([], [IDL.Vec(NovelPublic)], ['query']),
    'incrementReadCount' : IDL.Func([ChapterId], [], []),
    'joinCollabSession' : IDL.Func([ChapterId, NovelId], [], []),
    'leaveCollabSession' : IDL.Func([ChapterId], [], []),
    'publishChapter' : IDL.Func([ChapterId], [SaveDraftResult], []),
    'rateNovel' : IDL.Func([RatingRequest], [IDL.Bool], []),
    'removeCoAuthor' : IDL.Func([NovelId, IDL.Principal], [IDL.Bool], []),
    'removeFriend' : IDL.Func([UserId], [IDL.Bool], []),
    'saveChapterDraft' : IDL.Func([ChapterId, IDL.Text], [SaveDraftResult], []),
    'saveProgress' : IDL.Func([SaveProgressRequest], [IDL.Bool], []),
    'searchNovels' : IDL.Func([IDL.Text], [IDL.Vec(NovelPublic)], ['query']),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'updateChapter' : IDL.Func([ChapterId, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateNovel' : IDL.Func([NovelId, CreateNovelRequest], [IDL.Bool], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };