/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SaveProgressRequest {
    lastChapterNumber: bigint;
    lastChapterId: ChapterId;
    novelId: NovelId;
    percentComplete: number;
}
export type Timestamp = bigint;
export interface RatingRequest {
    novelId: NovelId;
    rating: bigint;
}
export interface CollabSessionPublic {
    lastUpdated: Timestamp;
    chapterId: ChapterId;
    novelId: NovelId;
    lastContent: string;
    activeEditors: Array<UserId>;
}
export interface ReadingProgressPublic {
    userId: UserId;
    lastChapterNumber: bigint;
    lastChapterId: ChapterId;
    novelId: NovelId;
    updatedAt: Timestamp;
    percentComplete: number;
}
export interface Chapter {
    id: ChapterId;
    title: string;
    content: string;
    chapterNumber: bigint;
    createdAt: Timestamp;
    novelId: NovelId;
}
export type ChapterId = bigint;
export interface UserProfilePublic {
    id: UserId;
    bio: string;
    username: string;
    chaptersRead: bigint;
    createdAt: Timestamp;
    novelsRead: bigint;
    avatarUrl: string;
    isAuthor: boolean;
}
export type UserId = Principal;
export type NovelId = bigint;
export interface NovelPublic {
    id: NovelId;
    title: string;
    ratingCount: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    authorName: string;
    description: string;
    coverImage: string;
    genre: string;
    coAuthors: Array<UserId>;
    totalReads: bigint;
    authorPrincipal: UserId;
    avgRating: number;
}
export interface CreateNovelRequest {
    title: string;
    tags: Array<string>;
    description: string;
    coverImage: string;
    genre: string;
}
export type SaveDraftResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface CreateChapterRequest {
    title: string;
    content: string;
    chapterNumber: bigint;
    novelId: NovelId;
}
export interface backendInterface {
    acceptFriendRequest(from: UserId): Promise<boolean>;
    addChapter(req: CreateChapterRequest): Promise<bigint>;
    addCoAuthor(novelId: NovelId, coAuthor: Principal): Promise<boolean>;
    becomeAuthor(): Promise<boolean>;
    createNovel(req: CreateNovelRequest, authorName: string): Promise<bigint>;
    createProfile(username: string, bio: string, avatarUrl: string): Promise<boolean>;
    declineFriendRequest(from: UserId): Promise<boolean>;
    filterByGenre(genre: string): Promise<Array<NovelPublic>>;
    getActiveSessions(novelId: NovelId): Promise<Array<CollabSessionPublic>>;
    getAllNovels(): Promise<Array<NovelPublic>>;
    getChapter(chapterId: ChapterId): Promise<Chapter | null>;
    getChapterDraft(chapterId: ChapterId): Promise<CollabSessionPublic | null>;
    getFriends(): Promise<Array<UserId>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getNovel(novelId: NovelId): Promise<NovelPublic | null>;
    getNovelChapters(novelId: NovelId): Promise<Array<Chapter>>;
    getPendingRequests(): Promise<Array<UserId>>;
    getProfile(userId: UserId): Promise<UserProfilePublic | null>;
    getProgress(novelId: NovelId): Promise<ReadingProgressPublic | null>;
    getReadingHistory(): Promise<Array<ReadingProgressPublic>>;
    getTopNovels(): Promise<Array<NovelPublic>>;
    incrementReadCount(chapterId: ChapterId): Promise<void>;
    joinCollabSession(chapterId: ChapterId, novelId: NovelId): Promise<void>;
    leaveCollabSession(chapterId: ChapterId): Promise<void>;
    publishChapter(chapterId: ChapterId): Promise<SaveDraftResult>;
    rateNovel(req: RatingRequest): Promise<boolean>;
    removeCoAuthor(novelId: NovelId, coAuthor: Principal): Promise<boolean>;
    removeFriend(friendId: UserId): Promise<boolean>;
    saveChapterDraft(chapterId: ChapterId, content: string): Promise<SaveDraftResult>;
    saveProgress(req: SaveProgressRequest): Promise<boolean>;
    searchNovels(term: string): Promise<Array<NovelPublic>>;
    searchUsers(term: string): Promise<Array<UserProfilePublic>>;
    sendFriendRequest(to: UserId): Promise<boolean>;
    updateChapter(chapterId: ChapterId, title: string, content: string): Promise<boolean>;
    updateNovel(novelId: NovelId, req: CreateNovelRequest): Promise<boolean>;
    updateProfile(username: string, bio: string, avatarUrl: string): Promise<boolean>;
}
import type { Chapter as _Chapter, CollabSessionPublic as _CollabSessionPublic, NovelPublic as _NovelPublic, ReadingProgressPublic as _ReadingProgressPublic, SaveDraftResult as _SaveDraftResult, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptFriendRequest(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addChapter(arg0: CreateChapterRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChapter(arg0);
            return result;
        }
    }
    async addCoAuthor(arg0: NovelId, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoAuthor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoAuthor(arg0, arg1);
            return result;
        }
    }
    async becomeAuthor(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.becomeAuthor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.becomeAuthor();
            return result;
        }
    }
    async createNovel(arg0: CreateNovelRequest, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNovel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNovel(arg0, arg1);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async declineFriendRequest(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.declineFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineFriendRequest(arg0);
            return result;
        }
    }
    async filterByGenre(arg0: string): Promise<Array<NovelPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByGenre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByGenre(arg0);
            return result;
        }
    }
    async getActiveSessions(arg0: NovelId): Promise<Array<CollabSessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSessions(arg0);
            return result;
        }
    }
    async getAllNovels(): Promise<Array<NovelPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNovels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNovels();
            return result;
        }
    }
    async getChapter(arg0: ChapterId): Promise<Chapter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapterDraft(arg0: ChapterId): Promise<CollabSessionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapterDraft(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapterDraft(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriends(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNovel(arg0: NovelId): Promise<NovelPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNovel(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNovel(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNovelChapters(arg0: NovelId): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNovelChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNovelChapters(arg0);
            return result;
        }
    }
    async getPendingRequests(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRequests();
            return result;
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(arg0: NovelId): Promise<ReadingProgressPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReadingHistory(): Promise<Array<ReadingProgressPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadingHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadingHistory();
            return result;
        }
    }
    async getTopNovels(): Promise<Array<NovelPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopNovels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopNovels();
            return result;
        }
    }
    async incrementReadCount(arg0: ChapterId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementReadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementReadCount(arg0);
            return result;
        }
    }
    async joinCollabSession(arg0: ChapterId, arg1: NovelId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCollabSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCollabSession(arg0, arg1);
            return result;
        }
    }
    async leaveCollabSession(arg0: ChapterId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveCollabSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveCollabSession(arg0);
            return result;
        }
    }
    async publishChapter(arg0: ChapterId): Promise<SaveDraftResult> {
        if (this.processError) {
            try {
                const result = await this.actor.publishChapter(arg0);
                return from_candid_SaveDraftResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishChapter(arg0);
            return from_candid_SaveDraftResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async rateNovel(arg0: RatingRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rateNovel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateNovel(arg0);
            return result;
        }
    }
    async removeCoAuthor(arg0: NovelId, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCoAuthor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCoAuthor(arg0, arg1);
            return result;
        }
    }
    async removeFriend(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async saveChapterDraft(arg0: ChapterId, arg1: string): Promise<SaveDraftResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChapterDraft(arg0, arg1);
                return from_candid_SaveDraftResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChapterDraft(arg0, arg1);
            return from_candid_SaveDraftResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProgress(arg0: SaveProgressRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgress(arg0);
            return result;
        }
    }
    async searchNovels(arg0: string): Promise<Array<NovelPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNovels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNovels(arg0);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async updateChapter(arg0: ChapterId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1, arg2);
            return result;
        }
    }
    async updateNovel(arg0: NovelId, arg1: CreateNovelRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNovel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNovel(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_SaveDraftResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaveDraftResult): SaveDraftResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chapter]): Chapter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CollabSessionPublic]): CollabSessionPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NovelPublic]): NovelPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReadingProgressPublic]): ReadingProgressPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
